### ISSUE TITLE
can't initialize private key

### ISSUE THREAD

**Issue by nadendlaprasad** [ShiftMediaProject/gnutls#10]
```
    gnutls_x509_privkey_t key;
   gnutls_x509_privkey_init(&key);
```

I am executing the above two lines of code in VS2017. I am not putting all the code as i have problem with only the above lines , `gnutls_x509_privkey_init` function always return -402 . Is this right or something wrong with this ?

**Comment by nadendlaprasad** [comment]
fixed this issue by initiating the context with `gnutls_global_init();`

**Comment by Sibras** [comment]
-402 means the library has not been initiliased properly.
I have just pushed an update that might fix the problem by automatically initialising the library. If you could try it out and test if it works now without needing gnutls_global_init.

**Comment by nadendlaprasad** [comment]
I downloaded latest version. many headers files are missing like earlier . I managed to get all except below two. 

```
Cannot open include file: 'ripemd160.h': No such file or directory (compiling source file ..\lib\accelerated\x86\sha-padlock.c)

Cannot open include file: 'camellia.h': No such file or directory (compiling source file ..\lib\accelerated\x86\aes-gcm-x86-ssse3.c)
```

could you please let me know where can i download these files ?

**Comment by nadendlaprasad** [comment]
Never mind, i got these files from nettle project.

**Comment by nadendlaprasad** [comment]
Thank you. new version fixed the issue. library is initializing properly without i manually invoke this gnutls_global_init();

But I'm still facing **Access violation writing location**  issue while generating private key using `gnutls_x509_privkey_generate(key, GNUTLS_PK_RSA, key_length, 0);`

**Comment by nadendlaprasad** [comment]
It's working well in debug mode(x64) but facing the same issue if i build the project in release mode(x64). I had to manually invoke `gnutls_global_init();` to fix this issue
